language: node_js
node_js:
  - 10
cache: npm
branches:
  only:
    - master
script:
  - hexo g
deploy:
  provider: pages
  cleanup: true
  github-token: $GH_TOKEN
  keep-history: false
  on:
    branch: master
  local-dir: public
